### ISSUE TITLE
Pixi.js v3

### ISSUE THREAD

**Issue by sseppola** [Izzimach/react-pixi#13]
Are there any plans to upgrade?

**Comment by Izzimach** [comment]
Yeah for sure, just not gotten around to it yet. Is there something in v3 you needed?

**Comment by sseppola** [comment]
Nothing in particular at the moment, I'm just getting my head around Pixi and integrating it into a React app. I just thought it was odd that there didn't seem to be any plans to upgrade when they have released a major version update. What needs to be done to upgrade to v3?

**Comment by Izzimach** [comment]
You should be able to just upgrade the pixi version in `package.json` and run it. Somehow I doubt it will be that easy, though :P 

The browserify-shim will probably have to be removed as well since v3 moved to a module-based architecture. The only other change I know about is the addition of ParticleContainer which (I think) replaces SpriteBatch. There are no doubt some other little changes but the only way to know is to try it.

**Comment by Izzimach** [comment]
Still need to bump version and deploy.

**Comment by sseppola** [comment]
awesome! :)
