### ISSUE TITLE
Question: Performance

### ISSUE THREAD

**Issue by quicksnap** [Izzimach/react-pixi#22]
A naive question I can answer myself, but wondering if you've tested it already.

Consider bunnymark: http://www.goodboydigital.com/pixijs/bunnymark/

If I ported bunnymark to react-pixi, would it bomb on performance? 

I'll be experimenting with it soon, but curious if you've messed with it.

**Comment by Izzimach** [comment]
It would totally bomb, assuming that you're doing the updates in React
components and having react propagate those changes to pixi. Part of the
reason is that the inner loop of bunnymark is very easy for the Javascript
JIT to optimize, but another part of the problem is the way React works.

A lot of React's performance depends on figuring out which things to update
and only updating those things. If you update everything every tick (which
you would with bunnymark) then React loses any performance advantage and
would in fact be horribly slow.

To get good performance there you would have to use a different data
representation so that there would be less updates sent. I did some
experiments with ClojureScript which is a bit more efficient but still
isn't great. https://github.com/Izzimach/chartreuse-vortex

**Comment by fabienbrooke** [comment]
You could encapsulate the bunnymark as a single React component and when its mounted start the updates using pure PIXI. So you'd be taking all those sprites and their updates out of React but you'd still have a way to pass information to the the component that's doing the bunnymark.
