### ISSUE TITLE
Installing 0.7.1 with npm.

### ISSUE THREAD

**Issue by netikular** [Izzimach/react-pixi#24]
I'm currently trying to upgrade to 0.7.1 however it appears that the package is not quite right on NPM.  I'm not seeing the react-pixi.js file in the node_modules/react-pixi

This is making my imports fail.

import ReactPixi from 'react-pixi';

Was there a change in usage recently?

**Comment by netikular** [comment]
It might be due to the fact that main in package.json es5/ReactPixi.js

 "https://github.com/Izzimach/react-pixi/blob/0385e04a44589b4358c3f229debdb8e7a73f0ca8/package.json#L26"

but it used to be src/ReactPixi.js

**Comment by netikular** [comment]
yep that's it, after installing everything I manually edited the package.json back to src/ instead of es5/ and everything builds and runs as expected.

**Comment by Izzimach** [comment]
Hm, well I intended to move ReactPIXI.js to ES6 and still provide an es5 version in es5.

There is a file in `es5` called `react-pixi-commonjs.js`. So really that's the file meant for people who aren't using babel/ES6.  Can you change `package.json` so that `main` points to `es5/react-pixi-commonjs.js` and verify that works? If so, that would be the change to make.

**Comment by netikular** [comment]
I don't have the es5 dir in my node_modules folder

**Comment by Izzimach** [comment]
It would be `node_modules/react-pixi/es5/` probably.

**Comment by netikular** [comment]
Yes it should be but it is not there.

I noticed a previous commit that excluded it from the package could that be why?

**Comment by netikular** [comment]
whoa, I lied… it is totally there.

trying your idea now.
