### ISSUE TITLE
React 0.14.1 Compatibility

### ISSUE THREAD

**Issue by parris** [Izzimach/react-pixi#27]
Looking at the package.json file, I see that we have a hard peerDependency on react@0.14.0. Can this be relaxed to ~0.14.0 ? I was attempting to use a webpack + react yeoman generator which set up 0.14.1 and the react-pixi install complained about it. As a result I had to fork, bump the version myself and build.

Thanks!

**Comment by Izzimach** [comment]
Since react-pixi depends on some React internals there is a possibility that even a bump in the patch level will cause problems, as seen in https://github.com/Izzimach/react-three/issues/23 . In light of that I decided that locking to a specific version would cause fewer problems.

Obviously I sometimes miss a React version bump (I guess they just release 0.14.2?) but I'll check this version. Hopefully it just means running the test suite and publishing a new version.

**Comment by Izzimach** [comment]
Commit 23d0cd78c95a90d5170cdb5c63d814746544fbe1 switched to 0.14.2
