### ISSUE TITLE
Packaging for cljsjs

### ISSUE THREAD

**Issue by weavejester** [Izzimach/react-pixi#43]
I've been attempting to write [cljsjs](https://cljsjs.github.io/) packaging script for react-pixi, in order to make it a bit easier to use in ClojureScript projects. I know you have a [Clojars package](https://clojars.org/org.clojars.haussman/react-pixi), but it's a little out of date, and I was thinking that perhaps bringing the package under the cljsjs umbrella would mean that you wouldn't need to keep updating it yourself.

Unfortunately I'm having trouble figuring out just how to automatically generate a suitable file. I'll keep plugging away at the problem regardless, but perhaps you can point me in the right direction? My understanding is that I want a file that contains both ReactPIXI.js and ReactPIXIMonkeyPatch.js, but not Pixi or React as those are already existing packages. Is a new webpack config required?

Thanks in advance for any help you can render.

**Comment by Izzimach** [comment]
Thanks for looking into this. I did make a clojurescript package at one
point but it didn't get much use. I considered putting it into cljsjs a
while ago but `boot` always barfed on my Windows machine so I just gave up.

Regarding packaging: react-pixi needs to access some of the internal code
in `React` which is why I am including it "inline" instead of as a separate
package. You could probably extract Pixi however. Is there already a cljsjs
package for Pixi?

You can probably reconfig webpack to reference Pixi as an external I guess
and then pack up both React and react-pixi into a cljsjs module. See
https://webpack.github.io/docs/library-and-externals.html to reference an
external library.

**Comment by weavejester** [comment]
Thanks for replying! There is indeed a Pixi package already, and I'm making progress with making a package for react-pixi.

One thing I don't understand though, is why does React need to be bundled with react-pixi? Even if the code is internal to React, you're monkeypatching it, right? So it shouldn't matter where React comes from, just as long as it's loaded?

**Comment by Izzimach** [comment]
Once React gets bundled up a lot of the internal functions are
inaccessable. You can `require('react')` but something like
`require('react/lib/ReactElement')` won't work. All the internal module
references are usually mangled by the bundling process.

I mean, I haven't looked at `cljsjs/react` but typically things like
`require('react/lib/ReactElement')` won't work with prepackaged modules
distributed by Facebook. Instead you need the `npm` version of the package
which lets you reach in and talk to internal modules.

I think long term there was some discussion about providing proper
injection points so that libraries like this didn't need access to React
internals but AFAIK they aren't quite there yet as of React 15.

**Comment by weavejester** [comment]
Thanks for the explanation! I've checked the cljsjs/react package and it has the same problem, in that the externs don't include the internal module references, so they're absent from the minified version.

I'm going to play around with this a little more and figure out the best way of handling this. There are quite a few references to the `cljsjs.react` namespace in other ClojureScript libraries, so I could create my own version of the namespace and exclude references to the cljsjs/react package, but maybe it's possible to have react-pixi use its own React, and allow everything else to use cljsjs/react.

**Comment by weavejester** [comment]
I've got a commit now weavejester/packages@7525419 that seems to work. Pixi is set as an external. React is compiled in. I haven't found any issues so far with using both cljsjs/react-pixi and cljsjs/react in the same project, but I'm going to try some more complex examples until I'm satisfied. Obviously it increases download size somewhat, but that seems like a reasonable tradeoff, and advanced compilation should reduce it further.

**Comment by weavejester** [comment]
react-pixi now exists as a [cljsjs package](https://clojars.org/cljsjs/react-pixi). Thanks for your help :)
