### ISSUE TITLE
Possible to avoid monkey patching react

### ISSUE THREAD

**Issue by stevenxxiu** [Izzimach/react-pixi#68]
I was looking at react-pixi but cannot use it right now due to monkey patching not able to work with loading react from a cdn, thus increasing the script size by too much. Is there a way at all to avoid monkey patching react?

[Someone else also mentioned](https://github.com/tomchentw/react-toastr/issues/86) that importing `react-dom/lib` has stopped working recently, so that might be another concern.

**Comment by Izzimach** [comment]
The problem with `react-dom` was fixed in 33e6d5.

Sadly, at this point there are many hooks into internal React code, even without the monkey-patching. Supposedly [React-fiber will provide better hooks for custom renderers](https://twitter.com/dan_abramov/status/798930380317298688) but until then we're stuck with this messy hack.
